name: Docs

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: Docs
        run: cd docs

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: Copy Helm files
        run: |
          cd ..
          cp index.yaml ./dist/index.yaml
          cp artifacthub-repo.yml ./dist/artifacthub-repo.yml


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

